title : PIF @ VA

safe: true
lsi: false
pygments: true
auto: true

source: veterans-affairs
destination: veterans-affairs

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

production_url : http://kinlane.github.io/veterans-affairs/

BASE_PATH : http://kinlane.github.io/veterans-affairs/

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
